// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var SF = require("../SF.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Project = require("./Project.bs.js");
var Resources = require("./Resources.bs.js");

console.log("Testing project:");

Project.runExample(undefined);

console.log("Testing connection:");

Curry._1(SF.Connection.runExample, undefined);

console.log("Testing resources:");

Resources.runExample(undefined);

/*  Not a pure module */
