// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Path = require("path");

function getAbsolutePath(path) {
  return Path.resolve(__dirname, path);
}

function readFile(path) {
  var absolutePath = Path.resolve(__dirname, path);
  return Fs.readFileSync(absolutePath, "utf8");
}

exports.getAbsolutePath = getAbsolutePath;
exports.readFile = readFile;
/* fs Not a pure module */
