// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Project$ReasonSfResources = require("./Project.bs.js");
var Connection$ReasonSfResources = require("./Connection.bs.js");

Project$ReasonSfResources.runExample(undefined);

Connection$ReasonSfResources.runExample(undefined);

/*  Not a pure module */
