// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Util$ReasonSfResources = require("./Util.bs.js");

var parsedData = Util$ReasonSfResources.decodeJSON(Util$ReasonSfResources.readFile("./../test-assets/test.json"));

console.log(parsedData.name);

exports.parsedData = parsedData;
/* parsedData Not a pure module */
