// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var example = "\n{\n  \"contacts\": [\n    \"harrymichal@seznam.cz\"\n  ],\n  \"description\": \"Unprivileged development environment\",\n  \"tenant\": \"local\",\n  \"website\": \"https://github.com/debarshiray/toolbox\",\n  \"name\": \"toolbox\",\n  \"source-repositories\": [\n    {\n      \"containers/toolbox\": {\n        \"connection\": \"github.com\",\n        \"zuul/exclude-unprotected-branches\": true\n      }\n    }\n  ]\n}\n";

function connection(param) {
  return Json_decode.field("connection", Json_decode.string, param);
}

function obj(param) {
  return Json_decode.dict(connection, param);
}

var MyDecode = {
  connection: connection,
  obj: obj
};

function parseSourceRepositories(json) {
  var st = Json.stringify(json);
  console.log("toto" + st);
  var a = Json_decode.dict(connection, json);
  console.log(Caml_array.caml_array_get(Object.keys(a), 0));
  return {
          name: "Test SR",
          connection: "github.com",
          zuul_exclude_unprotected_branches: true
        };
}

function parseProject(json) {
  var data = Json.parseOrRaise(json);
  return {
          contacts: Json_decode.field("contacts", (function (param) {
                  return Json_decode.list(Json_decode.string, param);
                }), data),
          description: Json_decode.field("description", Json_decode.string, data),
          tenant: Json_decode.field("tenant", Json_decode.string, data),
          website: Json_decode.field("website", Json_decode.string, data),
          name: Json_decode.field("name", Json_decode.string, data),
          source_repositories: Json_decode.field("source-repositories", (function (param) {
                  return Json_decode.array(parseSourceRepositories, param);
                }), data)
        };
}

function price(param) {
  return Json_decode.field("price", Json_decode.$$float, param);
}

function obj$1(param) {
  return Json_decode.dict(price, param);
}

var Decode = {
  price: price,
  obj: obj$1
};

var data = " {\n  \"AAPL\": { \"price\": 217.36 },\n  \"ABCD\": { \"price\": 240.5 }\n} ";

var decodedData = Json_decode.dict(price, Json.parseOrRaise(data));

console.log(decodedData["AAPL"]);

function runExample(param) {
  return parseProject(example);
}

exports.example = example;
exports.MyDecode = MyDecode;
exports.parseSourceRepositories = parseSourceRepositories;
exports.parseProject = parseProject;
exports.Decode = Decode;
exports.data = data;
exports.decodedData = decodedData;
exports.runExample = runExample;
/* decodedData Not a pure module */
