// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var SF_Connection = require("./SF/SF_Connection.bs.js");

var Connection = SF_Connection;

exports.Connection = Connection;
/* No side effect */
